const DIAGRAMM = {
  "Grundstufe": [
    "Besonderheiten beim Einsteigen",
    "Sitz einstellen",
    "Spiegel einstellen",
    "Lenkrad einstellen",
    "Kopfstütze einstellen",
    "Lenkradhaltung",
    "Pedale",
    "Gurt anlegen",
    "Schalt- oder Wählhebel",
    "Zündschloss",
    "Motor anlassen",
    "Anfahren",
    "Anhalten",
    "Schaltübungen 1-2",
    "Schaltübungen 2-3",
    "Schaltübungen 3-4",
    "Schaltübungen 4-3",
    "Schaltübungen 3-2",
    "Schaltübungen 2-1",
    "Lenkübungen"
  ],
  "Aufbaustufe": [
    "Rollen und Schalten",
    "Abbremsen und Schalten",
    "Bremsübungen degressiv",
    "Bremsübungen Zielbremsung",
    "Gefahrsituationen",
    "Gefälle",
    "Steigung",
    "Anhalten",
    "Anfahren",
    "Rückwärts",
    "Sichern",
    "Schalten",
    "Tastgeschwindigkeit",
    "Bedienungs- und Kontrolleinrichtungen",
    "Örtliche Besonderheiten"
  ],
  "Leistungsstufe": [
    "Fahrbahnbenutzung",
    "Einordnen",
    "Fahrstreifenwechsel links",
    "Fahrstreifenwechsel rechts",
    "Überholen",
    "Abbiegen rechts",
    "Abbiegen links",
    "Kreisverkehr",
    "Bahnübergang",
    "Schwierige Verkehrsführung",
    "Fußgängerüberwege",
    "Öffentliche Verkehrsmittel",
    "Ältere und Behinderte",
    "Kinder",
    "Schulbus",
    "Radfahrer",
    "Verkehrsberuhigter Bereich"
  ],
  "Grundfahraufgaben": [
    "Rückwärtsfahren",
    "Umkehren",
    "Gefahrenbremsung",
    "Einparken längs vorwärts links",
    "Einparken längs vorwärts rechts",
    "Einparken längs rückwärts links",
    "Einparken längs rückwärts rechts",
    "Einparken quer vorwärts links",
    "Einparken quer vorwärts rechts",
    "Einparken quer rückwärts links",
    "Einparken quer rückwärts rechts"
  ],
  "Überland": [
    "Angepasste Geschwindigkeit",
    "Abstand vorne",
    "Abstand hinten",
    "Abstand seitlich",
    "Verkehrszeichen",
    "Kreuzungen",
    "Kurven",
    "Steigungen",
    "Gefälle",
    "Alleen",
    "Überholen",
    "Wild und Tiere"
  ],
  "Autobahn": [
    "Fahrtplanung",
    "Einfahren in BAB",
    "Fahrstreifenwahl",
    "Geschwindigkeit",
    "Abstand vorne",
    "Abstand hinten",
    "Abstand seitlich",
    "Überholen",
    "Schilder und Markierungen",
    "Rastplätze",
    "Unfälle",
    "Dichter Verkehr",
    "Besondere Situationen",
    "Leistungsgrenze",
    "Ablenkung",
    "Konfliktsituationen",
    "Verlassen der BAB"
  ],
  "Dämmerung / Dunkelheit": [
    "Beleuchtung Kontrolle",
    "Beleuchtung einstellen",
    "Fernlicht",
    "Beleuchtete Straßen",
    "Unbeleuchtete Straßen",
    "Parken bei Dunkelheit",
    "Blendung",
    "Orientierung"
  ],
  "Reife- und Teststufe": [
    "Selbstständiges Fahren innerorts",
    "Selbstständiges Fahren außerorts",
    "Verantwortungsbewusstes Fahren",
    "Testfahrt unter Prüfungsbedingungen",
    "Wiederholung",
    "Leistungsbewertung"
  ]
};