const DIAGRAMM = {
  "Grundstufe – Einweisung und Bedienung": [
    "Besonderheiten beim Einsteigen",
    "Einstellen Sitz",
    "Einstellen Spiegel",
    "Einstellen Lenkrad",
    "Einstellen Kopfstütze",
    "Lenkradhaltung",
    "Pedale",
    "Gurt anlegen / anpassen",
    "Schalt-/Wählhebel",
    "Zündschloss",
    "Motor anlassen",
    "Anfahrübungen",
    "Anhalteübungen",
    "Schaltübungen hoch 1-2",
    "Schaltübungen hoch 2-3",
    "Schaltübungen hoch 3-4",
    "Schaltübungen runter 4-3",
    "Schaltübungen runter 3-2",
    "Schaltübungen runter 2-1",
    "Lenkübungen"
  ],
  "Aufbaustufe": [
    "Rollen und Schalten",
    "Abbremsen und Schalten",
    "Bremsübung degressiv",
    "Bremsübung Zielbremsung",
    "Gefahrsituationen",
    "Gefälle",
    "Steigung",
    "Manöver Anhalten",
    "Manöver Anfahren",
    "Manöver Rückwärts",
    "Manöver Sichern",
    "Manöver Schalten",
    "Tastgeschwindigkeit",
    "Bedienungs- und Kontrolleinrichtungen",
    "Örtliche Besonderheiten"
  ],
  "Leistungsstufe": [
    "Fahrbahnbenutzung Einordnen",
    "Fahrbahnbenutzung Markierungen",
    "Fahrstreifenwechsel links",
    "Fahrstreifenwechsel rechts",
    "Vorbeifahren / Überholen",
    "Abbiegen rechts",
    "Abbiegen links",
    "Abbiegen mehrspurig",
    "Radweg",
    "Sonderstreifen",
    "Straßenbahnen",
    "Einbahnstraßen",
    "Vorfahrt rechts vor links",
    "Vorfahrt Polizeibeamte",
    "Vorfahrt Grünpfeil",
    "Vorfahrt Grünpfeil-Schild",
    "Geschwindigkeit / Abstand",
    "Fußgängerüberwege",
    "Öffentl. Verkehrsmittel",
    "Ältere / Behinderte",
    "Einbahnstr. / Radfahrer",
    "Kinder",
    "Schulbus",
    "Radfahrer / Mofa",
    "Verkehrsberuhigter Bereich",
    "Schwierige Verkehrsführung",
    "Engpass",
    "Kreisverkehr",
    "Bahnübergang warten",
    "Hauptverkehrszeiten",
    "Partnerschaftliches Verhalten",
    "Schwung nutzen",
    "Fußgänger Schutzbereich"
  ],
  "Grundfahraufgaben": [
    "Rückwärtsfahren",
    "Umkehren",
    "Gefahrenbremsung",
    "Einparken längs vorwärts links",
    "Einparken längs vorwärts rechts",
    "Einparken längs rückwärts links",
    "Einparken längs rückwärts rechts",
    "Einparken quer vorwärts links",
    "Einparken quer vorwärts rechts",
    "Einparken quer rückwärts links",
    "Einparken quer rückwärts rechts"
  ],
  "Überlandfahrten": [
    "Angepasste Geschwindigkeit / Gangwahl",
    "Abstand vorne",
    "Abstand hinten",
    "Abstand seitlich",
    "Beobachtung / Spiegel",
    "Verkehrszeichen",
    "Kreuzungen / Einmündungen",
    "Kurven",
    "Steigungen",
    "Gefälle",
    "Alleen",
    "Überholen",
    "Liegenbleiben / Absichern",
    "Fußgänger",
    "Einfahren in Ortschaften",
    "Wild / Tiere",
    "Leistungsgrenze",
    "Ablenkung (Radio etc.)",
    "Orientierung"
  ],
  "Autobahn": [
    "Fahrtplanung",
    "Einfahren in BAB",
    "Fahrstreifenwahl",
    "Geschwindigkeit",
    "Abstand vorne",
    "Abstand hinten",
    "Abstand seitlich",
    "Überholen",
    "Schilder / Markierungen",
    "Vorbeifahren / Anschlussstellen",
    "Rast / Parkplätze / Tankstellen",
    "Verhalten bei Unfällen",
    "Dichter Verkehr / Stau",
    "Besondere Situationen",
    "Leistungsanforderungen",
    "Konfliktsituationen",
    "Verlassen der BAB"
  ],
  "Dämmerung / Dunkelheit": [
    "Beleuchtung Kontrolle",
    "Beleuchtung Einstellen",
    "Beleuchtung Benutzung",
    "Fernlicht",
    "Beleuchtete Straßen",
    "Unbeleuchtete Straßen",
    "Parken bei Dunkelheit",
    "Schlechte Witterung",
    "Bahnübergänge",
    "Tiere",
    "Unbeleuchtete Verkehrsteilnehmer",
    "Blendung",
    "Orientierung",
    "Abschlussbesprechung"
  ],
  "Reife- und Teststufe": [
    "Selbstständiges Fahren innerorts",
    "Selbstständiges Fahren außerorts",
    "Verantwortungsbewusstes Fahren",
    "Testfahrt unter Prüfungsbedingungen",
    "FAKT",
    "Andere Testfahrt",
    "Wiederholung / Vertiefung",
    "Leistungsbewertung"
  ],
  "Situative Bausteine – Fahrzeugtechnik": [
    "Reifen",
    "Profiltiefe",
    "Reifendruck",
    "Standlicht",
    "Abblendlicht",
    "Fernlicht",
    "Schlussleuchten mit Kennzeichenbeleuchtung",
    "Nebelschlussleuchte",
    "Warnblinkanlage",
    "Blinker",
    "Hupe",
    "Bremsleuchte",
    "Kontrollleuchten benennen",
    "Rückstrahler vorhanden",
    "Rückstrahler beschädigt",
    "Lenkschloss entriegeln",
    "Lenkradspiel prüfen",
    "Betriebsbremse prüfen",
    "Feststellbremse prüfen"
  ],
  "Heizung / Lüftung": [
    "Heizung",
    "Lüftung",
    "Klimaanlage",
    "Heckscheibenheizung",
    "Sonderausstattung"
  ],
  "Betriebs- und Verkehrssicherheit": [
    "Motoröl",
    "Kühlmittel",
    "Scheibenwaschflüssigkeit",
    "Warndreieck",
    "Verbandskasten",
    "Bordwerkzeug",
    "Scheiben / Wischer",
    "Spiegel",
    "Kennzeichen",
    "Beleuchtung außen",
    "Bremsen",
    "Ladung Sicherung",
    "Ladung Kennzeichnung"
  ],
  "Witterung": [
    "Lüftung bei Witterung",
    "Beleuchtung bei Witterung",
    "Scheibenwischer / Wasser",
    "Regen / Aquaplaning",
    "Wind / Sturm / Böen",
    "Schnee / Matsch / Eis"
  ]
};