const DIAGRAMM = {

"Grundstufe": [
"Besonderheiten beim Einsteigen",
"Sitz einstellen",
"Spiegel einstellen",
"Lenkrad einstellen",
"Kopfstütze einstellen",
"Lenkradhaltung",
"Pedale",
"Gurt anlegen / anpassen",
"Motor anlassen",
"Anfahr- / Anhalteübungen",
"Schalten hoch 1-2",
"Schalten hoch 2-3",
"Schalten hoch 3-4",
"Schalten runter 4-3",
"Schalten runter 3-2",
"Schalten runter 2-1",
"Lenkübungen"
],

"Aufbaustufe": [
"Rollen und Schalten",
"Abbremsen und Schalten",
"Bremsübung degressiv",
"Bremsübung Zielbremsung",
"Bremsübung Gefahrsituation",
"Gefälle Anhalten",
"Gefälle Anfahren",
"Gefälle Rückwärts",
"Gefälle Sichern",
"Gefälle Schalten",
"Steigung Anhalten",
"Steigung Anfahren",
"Steigung Rückwärts",
"Steigung Sichern",
"Steigung Schalten",
"Tastgeschwindigkeit",
"Bedienungs- und Kontrolleinrichtungen",
"Örtliche Besonderheiten"
],

"Leistungsstufe": [
"Fahrbahnbenutzung Einordnen",
"Fahrbahnbenutzung Markierungen",
"Fahrstreifenwechsel links",
"Fahrstreifenwechsel rechts",
"Vorbeifahren / Überholen",
"Abbiegen rechts",
"Abbiegen links",
"Abbiegen mehrspurig",
"Radweg",
"Sonderfahrstreifen",
"Straßenbahn",
"Einbahnstraße",
"Vorfahrt rechts vor links",
"Vorfahrt Polizeibeamte",
"Vorfahrt Grünpfeil",
"Vorfahrt Grünpfeil-Schild",
"Geschwindigkeit / Abstand",
"Fußgängerüberwege",
"Öffentlicher Verkehr",
"Ältere / Behinderte",
"Einbahnstraße / Radfahrer",
"Kinder",
"Schulbus",
"Radfahrer / Mofa",
"Verkehrsberuhigter Bereich",
"Schwierige Verkehrsführung",
"Engpass",
"Kreisverkehr",
"Bahnübergang warten",
"Kritische Verkehrssituation Hauptverkehrszeit",
"Partnerschaftliches Verhalten",
"Schwung nutzen",
"Fußgänger Schutzbereich"
],

"Grundfahraufgaben": [
"Rückwärtsfahren",
"Umkehren",
"Gefahrenbremsung",
"Einparken längs vorwärts links",
"Einparken längs vorwärts rechts",
"Einparken längs rückwärts links",
"Einparken längs rückwärts rechts",
"Einparken quer vorwärts links",
"Einparken quer vorwärts rechts",
"Einparken quer rückwärts links",
"Einparken quer rückwärts rechts"
],

"Überland": [
"Überland Angepasste Geschwindigkeit / Gangwahl",
"Überland Abstand vorne",
"Überland Abstand hinten",
"Überland Abstand seitlich",
"Überland Beobachtung / Spiegel",
"Überland Verkehrszeichen",
"Überland Kreuzungen / Einmündungen",
"Überland Kurven",
"Überland Steigungen",
"Überland Gefälle",
"Überland Alleen",
"Überland Überholen",
"Überland Liegenbleiben / Absichern",
"Überland Einfahren in Ortschaften",
"Überland Fußgänger",
"Überland Wild / Tiere",
"Überland Leistungsgrenze",
"Überland Ablenkung",
"Überland Orientierung"
],

"Autobahn": [
"Autobahn Fahrtplanung",
"Autobahn Einfahren",
"Autobahn Fahrstreifenwahl",
"Autobahn Geschwindigkeit",
"Autobahn Abstand vorne",
"Autobahn Abstand hinten",
"Autobahn Abstand seitlich",
"Autobahn Überholen",
"Autobahn Schilder / Markierungen",
"Autobahn Anschlussstellen",
"Autobahn Rastplätze",
"Autobahn Verhalten bei Unfällen",
"Autobahn Dichter Verkehr / Stau",
"Autobahn Leistungsgrenze",
"Autobahn Ablenkung",
"Autobahn Konfliktsituationen",
"Autobahn Verlassen"
],

"Dunkelheit": [
"Beleuchtung Kontrolle",
"Beleuchtung Einstellen",
"Beleuchtung Benutzung",
"Fernlicht",
"Beleuchtete Straßen",
"Unbeleuchtete Straßen",
"Parken",
"Schlechte Witterung",
"Bahnübergänge",
"Tiere",
"Unbeleuchtete Verkehrsteilnehmer",
"Blendung",
"Orientierung",
"Abschlussbesprechung"
],

"ReifeTest": [
"Selbstständiges Fahren innerorts",
"Selbstständiges Fahren außerorts",
"Verantwortungsbewusstes Fahren",
"Testfahrt Prüfungsbedingungen FAKT",
"Testfahrt Prüfungsbedingungen andere",
"Wiederholung / Vertiefung",
"Leistungsbewertung"
],

"SituativeBausteine": [
"Reifen Beschädigung",
"Reifen Profiltiefe",
"Reifen Reifendruck",
"Scheinwerfer Einschalten",
"Scheinwerfer Ausschalten",
"Standlicht",
"Abblendlicht",
"Fernlicht",
"Schlussleuchten mit Kennzeichenbeleuchtung",
"Nebelschlussleuchte",
"Warnblinkanlage",
"Blinker",
"Hupe",
"Bremsleuchte",
"Kontrollleuchten benennen",
"Rückstrahler vorhanden",
"Rückstrahler beschädigt",
"Lenkschloss entriegeln",
"Lenkspiel prüfen",
"Betriebsbremse",
"Feststellbremse"
],

"Fahrassistenzsysteme": [
"Assistenzsysteme Einschalten",
"Assistenzsysteme Ausschalten",
"Assistenzsysteme Anwenden"
],

"HeizungLueftung": [
"Heizung",
"Lüftung",
"Klimaanlage",
"Heckscheibenheizung",
"Beheizte Sonderausstattung",
"Keine unnötigen Verbraucher",
"Rechtzeitiges Abschalten"
],

"BetriebsVerkehrssicherheit": [
"Motoröl",
"Kühlmittel",
"Scheibenwaschflüssigkeit",
"Warndreieck",
"Verbandskasten",
"Bordwerkzeug",
"Zusätzliche Ausrüstung",
"Scheiben / Wischer",
"Spiegel",
"Kennzeichen",
"Beleuchtung",
"Bremsen",
"Ladungssicherung",
"Ladungskennzeichnung"
],

"Witterung": [
"Lüftung",
"Scheibenwischer / Wasser",
"Regen / Sprühnebel",
"Aquaplaning",
"Wind / Sturm / Böen",
"Schnee / Matsch",
"Eis"
]

};
